### ISSUE TITLE
Remove 'Programming Language :: Python :: 3.2', from setup.py

### ISSUE THREAD

**Issue by lorddaedra** [mailjet/mailjet-apiv3-python#10]

**Comment by arnaudbreton** [comment]
Hi @lorddaedra and thanks for your feedback and contribution.

We would love to know more about this PR to understand what the change is made for, from your perspective.

Thanks for your feedback

**Comment by lorddaedra** [comment]
@arnaudbreton, I feel, you ask about Django mail provider (topic of #9)?..

If you ask about removing `Programming Language :: Python :: 3.2` - it's just package meta-data..

Here https://github.com/mailjet/mailjet-apiv3-python/blob/master/.travis.yml you test latest versions of Python 2 and Python 3 (2.6, 2.7, 3.5, 3.6). It's correct...

And here https://github.com/mailjet/mailjet-apiv3-python/blob/master/setup.py
```
                 'Programming Language :: Python :: 2.6',
                 'Programming Language :: Python :: 2.7',
                 'Programming Language :: Python :: 3.2',
                 'Programming Language :: Python :: 3.5',
                 'Programming Language :: Python :: 3.6',
```

Here there is outdated version of Python (3.2), which is not supported by developers and not tested.

This metadata used for https://pypi.python.org/ and similar...

So just little typo, but as perfectionist I can't do not open that issue... :-)

**Comment by arnaudbreton** [comment]
@lorddaedra makes sense now, thanks for having spotted this detail, we're going to remove this line then
