### ISSUE TITLE
Add a "date" property on pypi

### ISSUE THREAD

**Issue by TheBlusky** [mailjet/mailjet-apiv3-python#15]
The mailjet_rest PyPi webpage (https://pypi.python.org/pypi/mailjet_rest) does not provide a "date" property.
It is used (in my case) by CI tools in order to give KPI about deprecation of libraries in "requirements.txt".

Would it be possible to provide one, so mailjet library does not trigger a warning when monitoring library version ?

Thanks in advance :-)

**Comment by Thoradin89** [comment]
Hello @TheBlusky ,

We'll deploy the updated wrapper on PyPi and add all the missing information.

Regards,
T.

**Comment by TheBlusky** [comment]
Wow, that is an old issue :-) 1 year and 1 day :-)

Thank you :-)

**Comment by abambova** [comment]
Hi @TheBlusky ,
I'll close the issue as the wrapper is updated with the missing information. Please feel free to open a new issue, if needed.
