### ISSUE TITLE
Impossible to know what is wrong

### ISSUE THREAD

**Issue by SBillion** [mailjet/mailjet-apiv3-python#20]
Hi, 

This is not possible to debug a template. I use a template with multiple variable and for loop. When I use it, I always get a 200, the email has been without any errors. But in fact, the mail has not been sent because something is wrong in my template or my vars but I can't know what...

**Comment by ngarnier** [comment]
hey @SBillion, you can add a `TemplateErrorReporting` field to your payload when using Send API ([documentation](https://dev.mailjet.com/guides/#send-api-json-properties)). You'll receive details about the errors on the email address you specified ([documentation for common templating errors](https://dev.mailjet.com/template-language/sendapi/#templates-error-management)).
