### ISSUE TITLE
How to add a contact to a list

### ISSUE THREAD

**Issue by herdani** [mailjet/mailjet-apiv3-python#22]
As I understand the Mailjet API logic and this wrapper, I though I could add a new contact to a list with the following command:

```
mailjet.contactslist_managecontact({"Email": "some@email", "Action": "addnoforce"}).get(id=some_contactslist_id)
```

But this doesn't work: `TypeError: 'contactslist' object is not callable`

How should I proceed ?

**Comment by eboisgon** [comment]
Hello herdani , 

I would advise you to have a look at the sample in the API guide [here](https://dev.mailjet.com/guides/?python#manage-contacts) 

This example should correspond to your needs 

```
id = '$LIST_ID'
data = {
  'Email': 'mrsmith@mailjet.com',
  'Name': 'MrSmith',
  'Action': 'addnoforce',
  'Properties': {
                "property1": "value",
                "propertyN": "valueN"
        }
}
result = mailjet.contactslist_managecontact.create(id=id, data=data)
print result.status_code
print result.json()
```

BR

**Comment by herdani** [comment]
Thanks, this works indeed!
And thanks for the link to the guide

One remark though: your sample works if I initiate the Mailjet client with v3, but not with v3.1
