### ISSUE TITLE
proxy dict

### ISSUE THREAD

**Issue by campbellmc** [mailjet/mailjet-apiv3-python#23]
Hi,
It would be great if kwargs were passed to request - so that a proxy dict could be provided to request.
They almost make it to the request on line 100 but are mysteriously missing there.

**Comment by Thoradin89** [comment]
Hello @campbellmc ,

I'll check if it can be useful to pass the proxy dict to the request. Perhaps it would be in the next version of the wrapper. Anyway, your request was taken into consideration. This ticket will now be closed.

Regards,
T.
