### ISSUE TITLE
Travis tests are broken because environment variables are missing

### ISSUE THREAD

**Issue by Natim** [mailjet/mailjet-apiv3-python#35]

**Comment by todorDim** [comment]
Hello Natim,

Indeed this is the case. Due to security reasons, they are removed from Travis. When an PR is accepted, unit tests are executed using internal key + secret. This is something we're looking to improve.

Regards,
T.

**Comment by Natim** [comment]
Do you know that you can store secrets in travis too? https://docs.travis-ci.com/user/encryption-keys/

**Comment by diskovod** [comment]
Updated Travis configuration
