### ISSUE TITLE
Mailjet_rest fails to install if requests is not already installed on Python 2.7

### ISSUE THREAD

**Issue by nymous** [mailjet/mailjet-apiv3-python#38]
**Steps to reproduce**

`requirements.txt`
```
mailjet_rest==1.3.3
```

Run
- `virtualenv -p python2.7 .venv`
- `source ./.venv/bin/activate`
- `pip install --no-cache-dir -r requirements.txt`

**Expected result**

Mailjet_rest is installed with its dependencies.

**Actual result**

```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting mailjet_rest==1.3.3 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/69/04/a92885c635ca412c8f5bdf3d11da6f619bbd4bce45c4e28189eeef10bd6a/mailjet_rest-1.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sgvuWV/mailjet-rest/setup.py", line 14, in <module>
        version = __import__('mailjet_rest').get_version()
      File "mailjet_rest/__init__.py", line 3, in <module>
        from mailjet_rest.client import Client
      File "mailjet_rest/client.py", line 7, in <module>
        import requests
    ImportError: No module named requests
```

I think it's because the `setup.py` file runs the `get_version()` function from a file that, through its imports, tries to import requests. This seems to happen before dependency resolution, so requests isn't there, and the import fails.

**Workaround**

First install requests with `pip install requests`, then install all requirements.

**Environment**

`pip --version`: pip 19.0.3
`python --version`: Python 2.7.16

**Comment by wapiflapi** [comment]
Seriously this is a big problem. It is not related to python 2.7, same behavior on python 3.

It prevents `mailjet_rest` from being added to the requirements of a project that uses an automated installation process.

**Comment by wapiflapi** [comment]
This is a real problem when using automated deploys / docket. Having to pre-install requests is an anti-pattern, not documented, and feels really dirty.

Can we please not have the `get_version()` hack in the `setup.py` that causes the unnecessary imports during installation?

**Comment by diskovod** [comment]
Updated setup.py. Fixed
