### ISSUE TITLE
Contact deletion does not work

### ISSUE THREAD

**Issue by siddhantgoel** [mailjet/mailjet-apiv3-python#39]
I'm trying to delete a contact using the client. The following does not work -

```python
v3_client = Client(auth=(public_key, secret_key))

response = v3_client.contact.get(id=email)

contact_id = response.json()['Data'][0]['ID']

v3_client.contact.delete(id=contact_id)  # returns a 401
```

I'm guessing this is because the default client uses `v3.1` while deleting contacts is only [supported under `v4`](https://dev.mailjet.com/guides/#delete-the-contact). But unfortunately, a `v4` client cannot delete a contact either.

```python
v4_client = Client(auth=(public_key, secret_key), version='v4')

v4_client.contact.delete(id=contact_id)  # returns a 404
```

This means currently we're using `mailjet_rest` to fetch the contact ID, and then using `requests` to delete it via the HTTP endpoint.

Could this behavior could also be supported by the `mailjet_rest` client?

**Comment by sowinski** [comment]
Hi,

did you found a workaround for this issue?

**Comment by siddhantgoel** [comment]
So far the only workaround is to use `requests` (or some other HTTP library of your choice) to make the request independent of `mailjet_rest`.

**Comment by suda** [comment]
This is due to two issues:
1) an incorrect endpoint URL. The client uses `/v4/REST/contact/:ID` but the one [mentioned in documentation](https://dev.mailjet.com/email/guides/contact-management/#gdpr-delete-contacts) is `/v4/contacts/:ID` (without `REST`).
2) V4 API uses `contacts` (plural) not `contact` as older versions.

I created #52 that should fix it, but in the meantime, I have an ugly monkey patch that does the same:

```python
from mailjet_rest.client import Config
import requests
from requests.compat import urljoin

class PatchedConfig(Config):
    """A monkey patched config, allowing to use V4 MailJet endpoints
    """
    def __getitem__(self, key):
        url = urljoin(self.api_url, self.version + '/')
        headers = {'Content-type': 'application/json', 'User-agent': self.user_agent}
        if key.lower() == 'contactslist_csvdata':
            url = urljoin(url, 'DATA/')
            headers['Content-type'] = 'text/plain'
        elif key.lower() == 'batchjob_csverror':
            url = urljoin(url, 'DATA/')
            headers['Content-type'] = 'text/csv'
        elif key.lower() != 'send' and self.version != 'v4':
            url = urljoin(url, 'REST/')
        url = url + key.split('_')[0].lower()
        return url, headers

def _get_mailjet(version="v3.1"):
    client = Client(
        auth=(MAILJET_API_KEY, MAILJET_API_SECRET), version=version
    )
    client.config = PatchedConfig(version=version)
    return client
```

You should be able to delete a contact using `_get_mailjet("v4").contacts.delete(CONTACT_ID)`
