### ISSUE TITLE
Cannot use contact.get to get email

### ISSUE THREAD

**Issue by ghost** [mailjet/mailjet-apiv3-python#43]
Ticket #1144279

**Doing this:**

filters = {
    "Limit": 1
}
id = '1111111111', (some contact id)

email = mailjet.contact.get(filters = filters, id=id)
print email.status_code
print email.json()

**I get this error response:**

400
{u'StatusCode': 400, u'ErrorInfo': u'', u'ErrorMessage': u'Unexpected error during GET: Invalid email address "(\'1111111111\',)", reason: "No @ character in mail"'}

**Comment by mskochev** [comment]
Hello, looking at the wrapper documentation (https://dev.mailjet.com/guides/#retrieve-a-contact) the id should be the contact email address.

**Comment by diskovod** [comment]
Regarding this issue, I didn't find any problems using Python 3+ and 2.7

Tried same code as you have: 
filters = {
"Limit": 1
}
id = "3136266005" ### or usermail

email = mailjet.contact.get(id=id, filters=filters)
print (email.status_code)
print (email.json())

And I got results on different versions. Also, documentation says that you can use email or id (https://dev.mailjet.com/email/guides/contact-management/) and it works.
