### ISSUE TITLE
Base url in documentation is incorrect

### ISSUE THREAD

**Issue by jpdvi** [mailjet/mailjet-apiv3-python#50]
> Base URL
The default base domain name for the Mailjet API is api.mailjet.com. You can modify this base URL by setting a value for api_url in your call:

The documentation states that the base url is `api.mailjet.com`, however the source shows it is set to `api.eu.mailjet.com`.  This should be reconciled either in the source or documentation.

**Comment by diskovod** [comment]
Decided to change the base URL on the wrapper side, so, for now, wrapper will use **api.mailjet.com** as mentioned in the documentation.
