### ISSUE TITLE
mailjet registration is broken

### ISSUE THREAD

**Issue by teamblubee** [mailjet/mailjet-apiv3-python#57]
Trying to register on mailjet.com; using a username@domain.me email address and I have been unable to get verification email response from mailjet.

Customer support is notoriously hard to get in touch with as well, maybe it has to do with the user@domain.me email address.

Nevertheless, the account info is in the system since I cannot create a new account with said email but i have been unable to get my verification email. The account has been in limbo for at least a month with no response from support.

Since you guys seem like a pretty small team, can I have someone take a look at the backend database to help get me my verification code?

best,
username@domain.me

**Comment by diskovod** [comment]
Sorry, but it's not related to Python wrapper. Closing this issue
