### ISSUE TITLE
Support recent Python versions

### ISSUE THREAD

**Issue by adamchainz** [mailjet/mailjet-apiv3-python#66]
The readme currently declares support for python only up to 3.6, and this is what's tested on Travis. That means the three most recent versions of Python aren't tested - 3.7, 3.8, and 3.9. Can you test with these? A project I'm working on is built with Python 3.8 and since we're using Mailjet I'm forced to proceed with the library whilst not being certain it will fully work.

Thanks!

**Comment by diskovod** [comment]
Hi, added support for Python 3.8. I think it will be enough for today. I guess that Python 3.9 support will be added in the near future. Thanks!

**Comment by adamchainz** [comment]
Thank you. 3.9 thankfully does not have many incompatible changes from 3.8.
