### ISSUE TITLE
Documentation - Wrong field names for attachments

### ISSUE THREAD

**Issue by Augustinio** [mailjet/mailjet-apiv3-python#68]
The [documentation](https://dev.mailjet.com/email/guides/send-api-V3/#send-with-attached-files) states that the required fields for attaching a file are:

- Content-type
- Filename
- content

The actual fields expected by the API are:

- ContentType
- Filename
- Base64Content

**Comment by Yenthe666** [comment]
Seems to be fixed by now :)

**Comment by diskovod** [comment]
Hi, it works as expected, can you please provide an example? Thanks
