### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by Natgho** [mailjet/mailjet-apiv3-python#89]
![image](https://github.com/mailjet/mailjet-apiv3-python/assets/6623948/f7c27708-2642-4d1b-9fca-efad4a304de4)

**Comment by Natgho** [comment]
up up up...

**Comment by Natgho** [comment]
@skupriienko Perhaps it is polite to write “thank you” to people who report bugs and there is no charge...

**Comment by skupriienko** [comment]
Thank you, @Natgho. I appreciate your contribution!

**Comment by Natgho** [comment]
politeness is the noblest language :) your welcome, I will continue to be around here as a strict follower 🤞
