### ISSUE TITLE
Django support

### ISSUE THREAD

**Issue by lorddaedra** [mailjet/mailjet-apiv3-python#9]
Please, add Django support (like in https://sendgrid.com/docs/Integrate/Frameworks/django.html)...

**Comment by lorddaedra** [comment]
https://docs.djangoproject.com/en/dev/topics/email/#defining-a-custom-email-backend

**Comment by lorddaedra** [comment]
I found https://github.com/kidig/django-mailjet, may be merge it and set official status as part of Python client?..

**Comment by arnaudbreton** [comment]
Hi @lorddaedra, thanks for sharing feedback here. We indeed have this community project which we didn't yet get a chance to give a deep review. Did you successfully make use of it on your end?

**Comment by lorddaedra** [comment]
Not yet. I'm new user of Mail Jet (used SMTP for testing). Going to try Mail Jet with it (https://github.com/kidig/django-mailjet) soon (in next 3 days)..

But it looks good and works based on feedback of other people..
I request some changes, I opened 

https://github.com/kidig/django-mailjet/issues/6
https://github.com/kidig/django-mailjet/issues/7
https://github.com/kidig/django-mailjet/issues/8

I hope with help of @kidig we fix them. 

After fix of this issues and my tests I expect I can recommend to provide link to this package or merge it may be..

Also you may be interested to check https://github.com/elbuo8/sendgrid-django, this project do same goal but for Send Grid.

**Comment by arnaudbreton** [comment]
@latanasov thanks for the very comprehensive feedback, very useful to us. Looking forward to hear back on how your tests go.

We'll look into it deeper in the coming weeks.
Best

**Comment by Thoradin89** [comment]
Hello all,

We're exploring this option. Since this issue is old it will be closed. Any new updates will be provided on the wiki and GITHUB.

Regards,
T.

**Comment by przem8k** [comment]
For anyone reading this in 2020, it seems that it's now easy to use Mailjet with Django using django-anymail . I wrote some notes based on my experience from a personal project @ https://pnote.eu/notes/django-app-engine-sending-email/
