### ISSUE TITLE
Public and Private key correct yet 401 Error

### ISSUE THREAD

**Issue by pagolina** [mailjet/mailjet-apiv3-python#90]
I have added and verify my domain dns successfully, generated apikey and secret key.
unfortunately, while integrating with python I keep getting the following error

"Unsuccessful: Status Code: "401" Message: "API key authentication/authorization failure. You may be unauthorized to access the API or your API key may be expired. Visit API keys management section to check your keys."

mailjet = Client(auth=(api_key, api_secret), version='v3.1')​

I printed that my public and private key were received in the function correctly, I have even use the key directly in the function yet the same error message. 

This is preventing our project from moving forward.

**Comment by DanyilNefodov** [comment]
Hi, @pagolina!

Could you provide please a request sample you are trying to execute?

Regards
