### ISSUE TITLE
parse_response will fail for e.g. 404 response

### ISSUE THREAD

**Issue by kontur** [mailjet/mailjet-apiv3-python#99]
Trying to debug why my API calls are failing I tried to look for places that might have debug logs. Trying to `parse_response` on a API call that returns 404 will fail, since there is no json to parse [here](https://github.com/mailjet/mailjet-apiv3-python/blob/446bc4b012bd4dc8dcf7aacbb890943240c0031b/mailjet_rest/client.py#L158).

Overall, it would be nice if there were a way to get better debug logging to find issues in API calls.

**Comment by skupriienko** [comment]
@kontur I'm trying to [address](https://github.com/mailjet/mailjet-apiv3-python/pull/111) your issue. 
Could you please provide more details about what you are trying to do and what is the result?

**Comment by skupriienko** [comment]
The issue solved here https://github.com/mailjet/mailjet-apiv3-python/pull/111
